### PR TITLE
adding browser and some food

### PR DESCRIPTION
**Pull request by trktuhin**
I have added uc browser and some food items

### CODE REVIEW

**Comment by HalfBlood-Prince** [comment]
There was a mistake with a food item.

**Comment by HalfBlood-Prince** [comment]
70377042-ambulance-wallpapers

**Comment by trktuhin** [comment]
[cv four.pptx](https://github.com/HalfBlood-Prince/Pull/files/1651683/cv.four.pptx)

**Comment by trktuhin** [comment]
finally fixed the spelling

**Comment by HalfBlood-Prince** [comment]
Thanks :)

**Pull request merged**
